[project]
name = "network-automation-temporal-project"
version = "0.1.0"
description = "Temporal workflow for network configuration management with Containerlab"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "temporalio",
    "requests",
]
